/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.janelas;

import java.awt.Color;

/**
 *
 * @author gabri
 */
public class JanelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form JanelaInicial
     */
    public JanelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        painelPrincipalPl = new javax.swing.JPanel();
        salvarBt = new javax.swing.JButton();
        editarBt = new javax.swing.JButton();
        labelPrincipalLb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDeTextoTx = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salvarBt.setText("Salvar");
        salvarBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salvarBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salvarBtMouseExited(evt);
            }
        });
        salvarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBtActionPerformed(evt);
            }
        });

        editarBt.setText("Editar");
        editarBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editarBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editarBtMouseExited(evt);
            }
        });

        labelPrincipalLb.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelPrincipalLb.setText("Bem-Vindo ao meu editor de Texto com Rich Text");

        areaDeTextoTx.setColumns(20);
        areaDeTextoTx.setRows(5);
        jScrollPane1.setViewportView(areaDeTextoTx);

        javax.swing.GroupLayout painelPrincipalPlLayout = new javax.swing.GroupLayout(painelPrincipalPl);
        painelPrincipalPl.setLayout(painelPrincipalPlLayout);
        painelPrincipalPlLayout.setHorizontalGroup(
            painelPrincipalPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalPlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(labelPrincipalLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelPrincipalPlLayout.createSequentialGroup()
                        .addComponent(salvarBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editarBt)))
                .addContainerGap())
        );
        painelPrincipalPlLayout.setVerticalGroup(
            painelPrincipalPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalPlLayout.createSequentialGroup()
                .addComponent(labelPrincipalLb)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(painelPrincipalPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarBt))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipalPl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipalPl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salvarBtActionPerformed

    private void salvarBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarBtMouseEntered
        salvarBt.setBackground(Color.gray);
    }//GEN-LAST:event_salvarBtMouseEntered

    private void salvarBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarBtMouseExited
        salvarBt.setBackground(Color.white);
    }//GEN-LAST:event_salvarBtMouseExited

    private void editarBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBtMouseEntered
        editarBt.setBackground(Color.gray);
    }//GEN-LAST:event_editarBtMouseEntered

    private void editarBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBtMouseExited
        editarBt.setBackground(Color.white);
    }//GEN-LAST:event_editarBtMouseExited
  
   
    public void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDeTextoTx;
    private javax.swing.JButton editarBt;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPrincipalLb;
    private javax.swing.JPanel painelPrincipalPl;
    private javax.swing.JButton salvarBt;
    // End of variables declaration//GEN-END:variables
}
