/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.janelas;
// teste git
import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyledDocument;

/**
 *
 * @author gabri
 */
public class JanelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form JanelaInicial
     */
    public JanelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        painelPrincipalPl = new javax.swing.JPanel();
        labelPrincipalLb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDeTextoTx = new javax.swing.JTextArea();
        barraPrincipalTB = new javax.swing.JToolBar();
        negritoTB = new javax.swing.JToggleButton();
        italicoTB = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPrincipalMB = new javax.swing.JMenu();
        salvarMB = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPrincipalLb.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelPrincipalLb.setText("Bem-Vindo ao meu editor de Texto com Rich Text");

        areaDeTextoTx.setColumns(20);
        areaDeTextoTx.setRows(5);
        jScrollPane1.setViewportView(areaDeTextoTx);

        barraPrincipalTB.setRollover(true);

        negritoTB.setText("Negrito");
        negritoTB.setFocusable(false);
        negritoTB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        negritoTB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        negritoTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negritoTBActionPerformed(evt);
            }
        });
        barraPrincipalTB.add(negritoTB);

        italicoTB.setText("Italico");
        italicoTB.setFocusable(false);
        italicoTB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        italicoTB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        italicoTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                italicoTBActionPerformed(evt);
            }
        });
        barraPrincipalTB.add(italicoTB);

        javax.swing.GroupLayout painelPrincipalPlLayout = new javax.swing.GroupLayout(painelPrincipalPl);
        painelPrincipalPl.setLayout(painelPrincipalPlLayout);
        painelPrincipalPlLayout.setHorizontalGroup(
            painelPrincipalPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalPlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(labelPrincipalLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barraPrincipalTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelPrincipalPlLayout.setVerticalGroup(
            painelPrincipalPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalPlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPrincipalLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barraPrincipalTB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPrincipalMB.setText("Arquivo");

        salvarMB.setText("salvar");
        salvarMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarMBActionPerformed(evt);
            }
        });
        menuPrincipalMB.add(salvarMB);

        jMenuBar1.add(menuPrincipalMB);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipalPl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipalPl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarMBActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Salvar arquivo");

        fileChooser.setSelectedFile(new File("novo_arquivo.txt"));
        
        int userSelection = fileChooser.showSaveDialog(null);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
                    File fileToSave = fileChooser.getSelectedFile();
                    try (FileWriter writer = new FileWriter(fileToSave)) {
                        writer.write(areaDeTextoTx.getText());
                        JOptionPane.showMessageDialog(null, "Arquivo salvo com sucesso!");
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "Erro ao salvar o arquivo.", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }
    }//GEN-LAST:event_salvarMBActionPerformed

    private void negritoTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negritoTBActionPerformed

    }//GEN-LAST:event_negritoTBActionPerformed

    private void italicoTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italicoTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_italicoTBActionPerformed

  
    public void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDeTextoTx;
    private javax.swing.JToolBar barraPrincipalTB;
    private javax.swing.JToggleButton italicoTB;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPrincipalLb;
    private javax.swing.JMenu menuPrincipalMB;
    private javax.swing.JToggleButton negritoTB;
    private javax.swing.JPanel painelPrincipalPl;
    private javax.swing.JMenuItem salvarMB;
    // End of variables declaration//GEN-END:variables
}
